add things unit tests
Antik88/ShortSharing pull request #24
Opened 2024-07-09 14:25 UTC by Antik88

2024-07-09 15:23 UTC, kalachck requested changes

2024-07-09 15:23 UTC, kalachck commented on ShortSharing.Tests/ThingServiceTests.cs
> +        }).CreateMapper();
It's better to mock mapper as well instead of the real one.

2024-07-09 15:23 UTC, kalachck commented on ShortSharing.Tests/ThingServiceTests.cs
> +        var id = Guid.NewGuid();
If you use AutoMock already why don't you pass guid id through the method arguments and use [Theory] and [AutoMock] attributes for that? Or you even can pass nay parameter while trying to setup GetByIdAsync method in repository, like this

```
_thingsRepository.GetByIdAsync(Arg.Any<Guid>(), default).ReturnsNull();
```
Please fix that issue for the whole test file.

2024-07-09 16:13 UTC, ZaytsevGleb approved these changes

2024-07-10 08:57 UTC, kalachck approved these changes

2024-07-10 09:00 UTC, kalachck approved these changes

2024-07-10 09:04 UTC, merged