add Dto validation
Antik88/ShortSharing pull request #27
Opened 2024-07-11 08:24 UTC by Antik88

2024-07-11 08:57 UTC, pavelGagarin0870 requested changes

2024-07-11 08:57 UTC, pavelGagarin0870 commented on ShortSharing.API/ShortSharing.API/Controllers/ThingController.cs
> +        var validationResult = _validator.Validate(thingDto);
validator.ValidateAndThrow(model);

2024-07-11 08:57 UTC, pavelGagarin0870 commented on .github/workflows/build.yml
> +          EXCLUDE_FROM_COVERAGE: "**/Program.cs, **/Extensions/*, **/Exceptions/**, **/Context/*, **/Migrations/*, **/DI/*, **/Entities/*, **/Validators/*, **/Enums/**/*, **/Repositories/**, **/Mappi
Validators can be covered by tests

2024-07-19 10:09 UTC, VadimZharikov approved these changes

2024-07-19 10:10 UTC, ZaytsevGleb approved these changes

2024-07-19 10:22 UTC, merged