Feature/rent service publisher
Antik88/ShortSharing pull request #34
Opened 2024-08-01 13:39 UTC by Antik88

2024-08-01 13:48 UTC, 5Ka-me requested changes

2024-08-01 13:48 UTC, 5Ka-me commented on Rent.Service/Rent.Service.Application/Rents/Commands/CreateRentCommand.cs
> +
Why is it here?

2024-08-01 13:48 UTC, 5Ka-me commented on Rent.Service/Rent.Service.Application/Rents/Commands/CreateRentCommand.cs
> +        var ownerModel = await serviceRequest.GetFromServiceById<UserModel>
What is the difference?

2024-08-01 13:48 UTC, 5Ka-me commented on Rent.Service/Rent.Service.Application/Rents/Commands/CreateRentCommand.cs
> +            throw new Exception();
What exception?

2024-08-01 14:11 UTC, 5Ka-me approved these changes

2024-08-06 19:45 UTC, Mmishaaa approved these changes

2024-08-06 19:45 UTC, Mmishaaa commented on Rent.Service/Rent.Service.API/Program.cs
> +                });
u may store these values in appsettings

2024-08-07 08:15 UTC, merged