add auth from auth0
Antik88/ShortSharing pull request #36
Opened 2024-08-12 11:10 UTC by Antik88

2024-08-12 13:53 UTC, moltenessence commented on User.Service/User.Service.API/Controllers/UserController.cs
> +    [Authorize (Roles = "Admin")]
could be extracted to constants

2024-08-12 13:53 UTC, moltenessence commented on User.Service/User.Service.API/Controllers/UserController.cs
> +    [Authorize (Roles = "User")]
same

2024-08-12 13:53 UTC, moltenessence commented on User.Service/User.Service.API/Controllers/UserController.cs
>          [FromBody] CreateUserDto userDto,
why you use CreateUserDto in patch method (and return this type as well)?

2024-08-12 14:01 UTC, ZaytsevGleb commented on User.Service/User.Service.BLL/Models/UserModel.cs
> +    public string? UserPicture { get; set; }
Why userPicture is string?

2024-08-12 14:01 UTC, ZaytsevGleb commented on User.Service/User.Service.API/DI/ServicesConfiguration.cs
>              options.Authority = $"https://{configuration["Auth0:Domain"]}/";
U can move full url to configuration

2024-08-15 18:03 UTC, 5Ka-me requested changes

2024-08-15 18:03 UTC, 5Ka-me commented on User.Service/User.Service.API/Program.cs
> +              builder.WithOrigins("http://localhost:5173")
Move this const into the `appsettings`

2024-08-17 14:29 UTC, ZaytsevGleb approved these changes

2024-09-02 11:33 UTC, pavelGagarin0870 approved these changes

2024-09-04 09:26 UTC, 5Ka-me approved these changes

2024-09-04 11:03 UTC, merged