add client app
Antik88/ShortSharing pull request #42
Opened 2024-09-18 11:53 UTC by Antik88

2024-09-19 11:14 UTC, Finka95 requested changes

2024-09-19 11:14 UTC, Finka95 commented on Client.App/src/App.tsx
> +  const theme = createTheme({
you can move it into a separete file

2024-09-19 11:14 UTC, Finka95 commented on Client.App/src/assets/bg.jpg
Try to avoid so big sizes of images. 1.7mb it's a very very big file

2024-09-19 11:14 UTC, Finka95 commented on Client.App/src/components/NavBar.tsx
> +    const drawerContent = (
it can be separate component

2024-09-19 11:14 UTC, Finka95 commented on Client.App/src/main.tsx
> +      audience: "https://sharing.com"
what is "https://sharing.com". By the way tou can move it into env file

2024-09-19 11:14 UTC, Finka95 commented on Client.App/src/pages/CatalogPage.tsx
> +        getCatalog({}).then(data => setCatalog(data));
add here conditions.
For example if you already have values. Just skip fetch

2024-09-20 11:13 UTC, MaliyOna approved these changes

2024-09-24 13:10 UTC, Finka95 approved these changes

2024-09-24 13:16 UTC, merged